### ISSUE TITLE
aca hace

### ISSUE THREAD

**Issue by Gianotti** [MoyaF/TP-1#2]
castea P1 a Espartano  ((Spartan)p1).getTolerancia + p1.getInterface_drink().drink() asi podes utilizar el int de tolerancia que es lo que no querias hacer

**Comment by Gianotti** [comment]
https://github.com/MoyaF/TP-1/blob/master/src/main/java/UTN/App.java#L43

**Comment by MoyaF** [comment]
No puedo, porque no tengo mas ese atributo. Aparte perdería el sentido el Strategy, en ese caso el código de tomar y de mear seria igual en las dos implementaciones
